### ISSUE TITLE
Add some emoji 🚀

### ISSUE THREAD

**Issue by josh-** [josh-/juniordev-hacktoberfest#2]
Let's make the README less bland ✨🎨🔥

**Comment by Lettisia** [comment]
Perfect I'm going to try this one. 🌈

**Comment by JianLoong** [comment]
Oh noes! I was after this one!

**Comment by Lettisia** [comment]
There can always be more emoji! :octocat:

**Comment by lorderikir** [comment]
Always more emoji :heart:
